#pragma once
//! Umbrella header: aggregates every Monte-Carlo node type (plus the shared
//! node-name suffixes) so a graph builder or consumer can pull in the whole node
//! catalogue with a single include instead of tracking each header. Add new node
//! headers here when introducing a node kind.
#include "node_names.hpp"
#include "autocallable_flow_node.hpp"
#include "asian_flow_node.hpp"
#include "ratchet_flow_node.hpp"
#include "digital_flow_node.hpp"
#include "barrier_flow_node.hpp"
#include "book_node.hpp"
#include "brownian_node.hpp"
#include "composite_correl_node.hpp"
#include "composite_vol_node.hpp"
#include "constant_node.hpp"
#include "contract_node.hpp"
#include "correlated_noise_node.hpp"
#include "dividend_node.hpp"
#include "drift_node.hpp"
#include "heston_variance_node.hpp"
#include "heston_spot_node.hpp"
#include "hull_white_factor_node.hpp"
#include "hull_white_integral_node.hpp"
#include "hybrid_spot_node.hpp"
#include "jump_node.hpp"
#include "absolute_basket_node.hpp"
#include "local_volatility_node.hpp"
#include "monte_carlo_node.hpp"
#include "noise_node.hpp"
#include "product_node.hpp"
#include "quanto_adjustment_node.hpp"
#include "rainbow_node.hpp"
#include "spot_diffusion_node.hpp"
#include "term_correl_node.hpp"
#include "vanilla_flow_node.hpp"
#include "variance_flow_node.hpp"
#include "yield_curve_node.hpp"
